# Generated by Django 4.2.3 on 2023-07-11 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_analysis', models.DateField(verbose_name='дата анализа')),
            ],
            options={
                'verbose_name': 'Анализ',
                'verbose_name_plural': 'Анализы',
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='диагноз')),
            ],
        ),
        migrations.CreateModel(
            name='NormalParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='показатель')),
                ('low_limit', models.IntegerField(verbose_name='нижний предел нормы')),
                ('high_limit', models.IntegerField(verbose_name='верхний предел нормы')),
            ],
            options={
                'verbose_name': 'Показатель нормы',
                'verbose_name_plural': 'Показатели нормы',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, verbose_name='ФИО пациента')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
            },
        ),
        migrations.CreateModel(
            name='DiagnosisByAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='calculator.analysis', verbose_name='анализ')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='calculator.diagnosis', verbose_name='диагноз')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField(verbose_name='результат')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='calculator.analysis', verbose_name='анализ')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='calculator.normalparameter', verbose_name='параметр')),
            ],
            options={
                'verbose_name': 'Показатель анализа',
                'verbose_name_plural': 'Показатели анализа',
            },
        ),
        migrations.AddField(
            model_name='analysis',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='calculator.patient', verbose_name='пациент'),
        ),
    ]
