# Generated by Django 4.2.3 on 2023-07-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, verbose_name='ФИО пациента')),
                ('diagnosis', models.CharField(blank=True, max_length=250, null=True, verbose_name='диагноз')),
                ('diagnosis_date', models.DateField(auto_now=True, verbose_name='дата диагноза')),
                ('RBC', models.IntegerField(verbose_name='уровень эритроцитов')),
                ('HGB', models.IntegerField(verbose_name='уровень гемоглобина')),
                ('HCT', models.IntegerField(verbose_name='гематокрит')),
                ('MCV', models.IntegerField(verbose_name='средн. объем эритроцита')),
                ('MCH', models.IntegerField(verbose_name='средн. эритроцитарный гемоглобин')),
                ('MCHC', models.IntegerField(verbose_name='средн. концентрация гемоглобина в эритроците')),
                ('RDW_CV', models.IntegerField(verbose_name='распределение эритроцитов по объёму, КВ')),
                ('RDW_SD', models.IntegerField(verbose_name='распределение эритроцитов по объёму, СКВ')),
                ('ferritin', models.IntegerField(verbose_name='ферритин')),
                ('transferrin', models.IntegerField(verbose_name='трансферрин')),
                ('TIBC', models.IntegerField(verbose_name='TIBC')),
                ('fe', models.IntegerField(verbose_name='железо')),
                ('B9', models.IntegerField(verbose_name='витамин B9')),
                ('B12', models.IntegerField(verbose_name='витамин B12')),
                ('total_bilirubin', models.IntegerField(verbose_name='общий билирубин')),
                ('LDH', models.IntegerField(verbose_name='ЛДГ')),
            ],
            options={
                'verbose_name': 'Анализ',
                'verbose_name_plural': 'Анализы',
            },
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='parameter',
        ),
        migrations.RemoveField(
            model_name='diagnosisbyanalysis',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='diagnosisbyanalysis',
            name='diagnosis',
        ),
        migrations.AddField(
            model_name='normalparameter',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='описание показателя'),
        ),
        migrations.AlterField(
            model_name='normalparameter',
            name='name',
            field=models.CharField(max_length=250, verbose_name='название показателя'),
        ),
        migrations.DeleteModel(
            name='Analysis',
        ),
        migrations.DeleteModel(
            name='AnalysisResult',
        ),
        migrations.DeleteModel(
            name='Diagnosis',
        ),
        migrations.DeleteModel(
            name='DiagnosisByAnalysis',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
