# Generated by Django 4.2.3 on 2023-07-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_alter_examination_b12_alter_examination_b9_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='homocystein',
            field=models.FloatField(blank=True, null=True, verbose_name=' гомоцистеин'),
        ),
    ]
